### ISSUE TITLE
Ordering can't span tables on non-relational backends

### ISSUE THREAD

**Issue by N3TC4T** [Knotis/djangocassandra#59]
Hey 

How can i manage this error ?

>./manage syncdb
 django.db.utils.DatabaseError: Ordering can't span tables on non-relational backends (content_type__app_label).

Even I've tried on django-norel but i get different error .

**Comment by sethdenner** [comment]
If you are using any of the apps that come with django the data models aren't non-relational friendly. You can install and use https://www.allbuttonspressed.com/projects/django-dbindexer to allow django to do JOIN's in memory however if you are planning on heavily using any of those models you will probably have to implement them in a non-relational way in order to achieve top performance and scalability in your app.

**Comment by N3TC4T** [comment]
Thanks for the answer .
we decided to separating our django auth models that using relational database backend (used postgre db)  and our big data model , and it's working well .
Do you think is this a good decision ?

**Comment by sethdenner** [comment]
yep, it's the decision I wish I made when I started my project ;)
